import React from 'react'
import Head from 'next/head'

function HeadComponent() {
  return (
    <Head>
        <title>Learning Next.js framework</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="google-site-verification" content="r0WSNtAtq-pKuuGDTtXp3oFhJRQSxkldUKsErt74l4w" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  )
}

export default HeadComponent